theme: jekyll-theme-minimal
title: Leo's test page
description: A template website for ADA trying to figure out if I can use plotly
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
